networks:
  app:
    driver: bridge
#  web:
#    external: true

services:
  app:
    image: 'afladev/php:8.3-dev'
    working_dir: '/app'
    volumes:
      - '.:/app'
    networks:
        - app
#        - web
    ports:
      - ${APP_PORT:-80}:80
      - ${VITE_PORT:-5173}:${VITE_PORT:-5173}
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.boilerplate.entrypoints=web"
#      - "traefik.http.routers.boilerplate.rule=Host(`${APP_HOST}`)"

  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '${FORWARD_MYSQL_PORT:-3306}:3306'
    networks:
      - app

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - app
